strictness: veryhigh
max-line-length: 120
autodetect: yes
python-targets:
    - 3
pylint:
  disable:
    - no-self-use
    - too-few-public-methods
    - super-init-not-called
pep8:
  disable:
    - E302
